#!/usr/bin/env python3
"""Assign colours to the claims of a module and write them into the model text.

Usage:  python tools/assign_colors.py tools/marks/m1.json

For every claim without a "color" a palette colour (1..10, see mark_pdfs.py) is chosen such that two claims that are
marked in the same paper never share a colour (colours may be reused across papers).  The model text refers to claims
by name, \\mk{M1-claim}{text} (underscores of the claim id become hyphens); marks_claims.tex, regenerated here, maps
every name to its colour.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NCOL = 10


def assign(spec):
    claims = spec["claims"]
    papers_of = {c: set() for c in claims}
    for paper, marks in spec["papers"].items():
        for m in marks:
            papers_of[m["claim"]].add(paper)
    order = list(claims)
    for i, cid in enumerate(order):
        if claims[cid].get("color"):
            continue
        used = {claims[o]["color"] for o in order if o != cid and claims[o].get("color") and papers_of[o] & papers_of[cid]}
        # neighbours in reading order get different colours where possible
        prev = {claims[o]["color"] for o in order[max(0, i - 3):i] if claims[o].get("color")}
        cands = [c for c in range(1, NCOL) if c not in used] or [c for c in range(1, NCOL + 1) if c not in used]
        if not cands:
            raise SystemExit(f"no free colour for claim {cid}: more than {NCOL} claims in one paper")
        pick = [c for c in cands if c not in prev] or cands
        count = {c: sum(1 for o in claims.values() if o.get("color") == c) for c in pick}
        claims[cid]["color"] = min(pick, key=lambda c: (count[c], c))


def write_claims_file():
    """Regenerate marks_claims.tex from all tools/marks/m*.json: one \\colorlet per claim (name M<n>-<claim>)."""
    lines = ["% Generated by tools/assign_colors.py -- do not edit.",
             "% \\mk{M1-claim}{text} uses the colour of the claim; the same colour marks the supporting passage in the paper."]
    for fp in sorted((ROOT / "tools" / "marks").glob("m*.json"), key=lambda p: (len(p.stem), p.stem)):
        spec = json.loads(fp.read_text())
        mod = spec["module"]
        for cid, c in spec["claims"].items():
            if isinstance(c.get("color"), int) and mod != "M0":
                lines.append("\\colorlet{mk%s-%s}{mk%d}" % (mod, cid.replace("_", "-"), c["color"]))
    (ROOT / "marks_claims.tex").write_text("\n".join(lines) + "\n")


def main(path):
    p = Path(path)
    spec = json.loads(p.read_text())
    assign(spec)
    p.write_text(json.dumps(spec, indent=1, ensure_ascii=False) + "\n")
    write_claims_file()
    unused = [c for c in spec["claims"] if not any(m["claim"] == c for ms in spec["papers"].values() for m in ms)]
    if unused:
        print("claims without a mark in any paper:", ", ".join(unused))
    print("colours:", {c: v["color"] for c, v in spec["claims"].items()})


if __name__ == "__main__":
    main(sys.argv[1])
